AllCops:
  Exclude:
    - "node_modules/**/*" # rubocop config/default.yml
    - "vendor/**/*"       # rubocop config/default.yml
    - "db/schema.rb"

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# 文字列を括るのにシングルクォートを使用する
Style/StringLiterals:
  EnforcedStyle: single_quotes
